{
 "title": "Thermostat",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Heating enabled",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ch_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Room",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_setpoint", "legendFormat": "desired" },
    { "expr": "room_temperature", "legendFormat": "current" }
   ]
  },
  {
   "title": "Room setpoint / temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "room_setpoint", "legendFormat": "desired" },
    { "expr": "room_temperature", "legendFormat": "current" }
   ]
  },
  {
   "title": "Boiler setpoint / temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "boiler_setpoint", "legendFormat": "{{__name__}}" },
    { "expr": "boiler_temperature", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "PID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "pid_p", "legendFormat": "P" },
    { "expr": "pid_i", "legendFormat": "I" },
    { "expr": "pid_d", "legendFormat": "D" }
   ]
  }
 ]
}