service:
  type: NodePort
  externalTrafficPolicy: Local
  annotations:
    {}
    # metallb.universe.tf/allow-shared-ip: pi-hole

ports:
  mqtt:
    port: 1883
    # sets consistent nodePort, required to set service.type=NodePort
    nodePort: 31883
    protocol: TCP
  websocket:
    port: 9090
    protocol: TCP
